# Orchestrator API base spec
openapi: 3.0.0
info:
  title: "Active Matching API"
  version: 1.0.0
  description: "API for finding matching participant records across all participating states."
tags:
  - name: "Match"
servers:
  - url: "/v2"
paths:
  /find_matches:
    $ref: './find.yaml'
  /find_matches_by_pii:
    $ref: './find-pii.yaml'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
