openapi: 3.0.0
info:
  title: "Duplicate Participation API"
  version: 1.0.0
  description: "The API where matching will occur"
servers:
  - url: "/v2"
paths:
  /find_matches:
    $ref: '../../match/docs/openapi/orchestrator/find.yaml'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
